[package]
name = "wiki_bot"
version = "1.1.0"
authors = ["Andrei Tanana <andrei.tanana@deltatre.it>"]
edition = "2021"

[dependencies]
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
select = "0.5.0"
regex = "1.1.6"
once_cell = "1.16.0"